Repository FRONTENDSCHOOL8/cafeWhere, pull requests merged in 2024-02, with the labels that each got.

#10 체크박스 마크업 및 기능구현(중간만 구현) -> 기능은 추후 예정
  public/ischeckbox.svg
  public/uncheckbox.svg
  src/App.jsx
  src/components/atoms/inputCheckBox.jsx
  src/components/atoms/test.jsx
  src/styles/main.css
Labels: 🎨 HTML & CSS, ✨ Feature, 😍 A11Y, ❓ Question

#17 [✨Feat]: CafeListItem 컴포넌트 및 Wish 컴포넌트 구현
  public/cafeList.jpg
  public/images/wish/favorites-remove.png
  public/images/wish/favorites.png
  src/components/atoms/Wish/Wish.jsx
  src/components/atoms/index.jsx
  src/components/organisms/CafeListItem/CafeListItem.jsx
Labels: 🎨 HTML & CSS, ✨ Feature

#18 [✨Feat] HeaderSwiper, 탭 바, 헤더, 위치 화살표 마크업과 기존 css 수정 및 이미지 추가
  public/images/main/header/arrow-down.svg
  public/images/main/header/mainLogo.svg
  public/images/main/header/mapLogo.svg
  public/images/main/header/searchIcon.svg
  public/images/main/swiper/leftArrow.svg
  public/images/main/swiper/rightArrow.svg
  public/images/main/swiper/swiperBigImg.svg
  public/images/main/swiper/swiperBigImg2.svg
  public/images/main/swiper/swiperBigImg3.svg
  public/images/main/swiper/swiperimg1.svg
  public/images/main/swiper/swiperimg2.svg
  public/images/main/swiper/swiperimg3.svg
  public/images/main/tabbar/HOME-B.svg
  public/images/main/tabbar/HOME-R.svg
  public/images/main/tabbar/cafeicon-b.svg
  public/images/main/tabbar/cafeicon-r.svg
  public/images/main/tabbar/myicon-b.svg
  public/images/main/tabbar/myicon-r.svg
  public/images/main/tabbar/review-b.svg
  public/images/main/tabbar/review-r.svg
  public/images/main/tabbar/wish-b.svg
  public/images/main/tabbar/wish-r.svg
  src/App.jsx
  src/components/HeaderSwiper/HeaderSwiper.jsx
  src/components/atoms/HeaderBar/HeaderBar.jsx
  src/components/atoms/MainHeader/MainHeader.jsx
  src/components/atoms/TabBar/TabBar.jsx
  src/components/atoms/index.jsx
  src/pages/Preparing/Preparing.jsx
Labels: 🎨 HTML & CSS, ✨ Feature, 😍 A11Y

#16 로그인 버튼, 소셜 로그인 버튼 마크업 (진행중)
  public/kakao.svg
  src/components/atoms/Divider/Divider.jsx
  src/components/atoms/LoginButton/LoginButton.jsx
  src/components/atoms/SIgnUpLink/SignUpLink.jsx
  src/components/atoms/SocialLoginButton/SocialLoginButton.jsx
Labels: 🎨 HTML & CSS
