Repository FRONTENDSCHOOL8/cafeWhere, pull requests merged in 2024-03, with the labels that each got.

#19 [✨Feat]: Category 컴포넌트 구현
  src/components/atoms/CategoryItem/CategoryItem.jsx
  src/components/atoms/index.jsx
  src/components/organisms/Category/Category.jsx
Labels: 🎨 HTML & CSS

#22 [✨Feat] 로그인 페이지 컴포넌트 및 라우터 기능
  public/images/LoginLogo.svg
  public/images/bigLogo.svg
  src/App.jsx
  src/components/ProductTab/ProductTab.jsx
  src/components/atoms/HeaderBar/HeaderBar.jsx
  src/components/atoms/LoginButton/LoginButton.jsx
  src/components/atoms/SIgnUpLink/SignUpLink.jsx
  src/components/molcules/InputField/InputField.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/Preparing/Preparing.jsx
  src/pages/RootLayout/RootLayout.jsx
  src/routes/index.jsx
  src/routes/navigation.jsx
  src/utils/pocketbase.js
Labels: 🎨 HTML & CSS, ✨ Feature, 🔁 refactor

#23 [♻️Refactor]: 야무쌤의 리팩토링
  src/components/atoms/Divider/Divider.jsx
  src/components/atoms/Divider/Divider.stories.jsx
  src/components/atoms/ErrorMessage/ErrorMessage.jsx
  src/components/atoms/ErrorMessage/ErrorMessage.stories.jsx
  src/components/atoms/PasswordIcon/PasswordIcon.jsx
  src/components/atoms/PasswordIcon/PasswordIcon.stories.jsx
  src/components/atoms/UserInfoInput/UserInfoInput.jsx
  src/components/atoms/UserInfoInput/UserInfoInput.stories.jsx
  src/components/atoms/UserInfoLabel/UserInfoLabel.stories.jsx
  src/components/molecules/InputField/InputField.jsx
  src/components/molecules/InputField/InputField.stories.jsx
  src/components/molecules/index.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/components/organisms/LoginInput/LoginInput.stories.jsx
Labels: ❓ Question

#24 회원가입 페이지 체크박스 기능 폴더 정리
  public/images/join/ischeckbox.svg
  public/images/join/uncheckbox.svg
  public/images/main/test.png
  public/images/wish/favorites-remove.svg
  public/images/wish/favorites.svg
  src/App.jsx
  src/components/SwiperCafeList/CategoryCafeList.jsx
  src/components/SwiperCafeList/SwiperCafeList.jsx
  src/components/atoms/Wish/Wish.jsx
  src/components/organisms/CheckBox/JoinInputCheckBox.jsx
  src/components/organisms/CheckBox/LastCheckBox.jsx
  src/components/organisms/JoinInput/JoinInput.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
Labels: 🎨 HTML & CSS, ✨ Feature, 😍 A11Y, 😯 typo

#26 SearchLoginPage 컴포넌트와 라우터 기능 연결
  public/images/biglogo2.svg
  src/components/HeaderSwiper/HeaderSwiper.jsx
  src/components/atoms/HeaderBar/HeaderBar.jsx
  src/components/atoms/LoginButton/LoginButton.jsx
  src/components/atoms/MainHeader/MainHeader.jsx
  src/components/atoms/TabBar/TabBar.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/RootLayout/RootLayout.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
  src/routes/navigation.jsx
Labels: 🎨 HTML & CSS, ✨ Feature, ✂️ Modify

#28 Footer, Hashtag 컴포넌트 구현 & LoginButton, SignUpLink CSS 수정
  src/components/atoms/Footer/Footer.jsx
  src/components/atoms/Hashtag/Hashtag.jsx
  src/components/atoms/LoginButton/LoginButton.jsx
  src/components/atoms/SIgnUpLink/SignUpLink.jsx
Labels: 🎨 HTML & CSS, ✨ Feature, ✂️ Modify

#33 [✨Feat] : 로그인 기능 구현
  src/App.jsx
  src/components/atoms/HeaderBar/HeaderBar.jsx
  src/components/atoms/LoginButton/LoginButton.jsx
  src/components/atoms/MainHeader/MainHeader.jsx
  src/components/molecules/InputField/InputField.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
Labels: 📮 API, ✨ Feature, ✂️ Modify

#37 mypage 컴포넌트와 회원가입 기능 구현
  public/images/mypageicon.svg
  src/components/atoms/HeaderBar/HeaderBar.jsx
  src/components/atoms/LoginButton/LoginButton.jsx
  src/components/atoms/TabBar/TabBar.jsx
  src/components/organisms/CheckBox/JoinInputCheckBox.jsx
  src/components/organisms/JoinInput/JoinInput.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/pages/JoinPage/JoinPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
  src/routes/navigation.jsx
Labels: 📮 API, 🎨 HTML & CSS, ✨ Feature, ✂️ Modify

#38 Footer, Hashtag 수정 & CafeInfoTab, ReviewButton, ReviewKeywordRank 컴포넌트 구현
  src/components/atoms/CafeInfoTab/CafeInfoTab.jsx
  src/components/atoms/Footer/Footer.jsx
  src/components/atoms/Hashtag/Hashtag.jsx
  src/components/atoms/ReviewButton/ReviewButton.jsx
  src/components/atoms/ReviewKeywordsRank/ReviewKeywordsRank.jsx
  src/components/atoms/TabButton/TabButton.jsx
  src/styles/tailwind.css
Labels: 🎨 HTML & CSS, ✨ Feature, 🔁 refactor, ✂️ Modify

#41 TabBar 상태관리 수정
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/HeaderSwiper/HeaderSwiper.jsx
  src/components/atoms/TabBar/TabBar.jsx
  src/components/organisms/JoinInput/JoinInput.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/Preparing/Preparing.jsx
  src/pages/RootLayout/RootLayout.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
  src/store/useTabStore.js
Labels: ✨ Feature, ✂️ Modify, 🔧setting

#47 회원 가입 구현 및 유저 정보 저장
  src/components/organisms/Category/Category.jsx
  src/components/organisms/JoinInput/JoinInput.jsx
  src/components/organisms/LoginInput/LoginInput.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/Preparing/Preparing.jsx
  src/routes/navigation.jsx
  src/store/useLoginStore.js
Labels: 📮 API, ✨ Feature, ✂️ Modify

#53 검색 페이지 마크업 구현
  public/cup.png
  public/glass.svg
  public/images/ back.svg
  src/components/atoms/NoResult/NoResult.jsx
  src/components/atoms/ReviewButton/ReviewButton.jsx
  src/components/atoms/Searchbar/Searchbar.jsx
  src/components/atoms/back/back.jsx
  src/components/molecules/SearchField/SearchField.jsx
  src/pages/NoResultPage/NoResultPage.jsx
  src/pages/ResultListPage/ResultListPage.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: 🎨 HTML & CSS

#56 Feature/tab bar store
  src/components/atoms/FetchingData/FetchingData.jsx
  src/components/atoms/ReviewInfo/ReviewInfo.jsx
  src/components/atoms/TabBar/TabBar.jsx
  src/components/organisms/DetailReviewList/ReviewList.jsx
  src/components/organisms/JoinInput/JoinInput.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyReviewPage/MyReviewPage.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
  src/routes/navigation.jsx
Labels: 📮 API, ✨ Feature

#60 리뷰 컴포넌트
  public/images/coffeepull1.svg
  public/images/coffeepull2.svg
  src/components/atoms/RatingScore/RatingScore.jsx
  src/components/organisms/ReviewWrite/ReviewWrite.jsx
  src/pages/MyReviewPage/MyReviewPage.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
  src/utils/getDocumentTitle.js
Labels: 📮 API, 🎨 HTML & CSS, ✨ Feature

#65 나만의 리뷰 컴포넌트 기능 구현
  src/components/atoms/HeaderBar/HeaderBar.jsx
  src/components/atoms/SignUpZone/SignUpZone.jsx
  src/components/organisms/DetailReviewList/ReviewList.jsx
  src/components/organisms/ReviewWrite/ReviewWrite.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MyReviewPage/MyReviewPage.jsx
  src/pages/SelectLoginPage/SelectLoginPage.jsx
Labels: 📮 API, 🎨 HTML & CSS, ✨ Feature

#74 리뷰 작성 컴포넌트와 리팩토링
  public/images/main/swiper/swipermainimage1.svg
  public/images/main/swiper/swipermainimage2.svg
  public/images/main/swiper/swipermainimage3.svg
  src/components/HeaderSwiper/HeaderSwiper.jsx
  src/components/atoms/Wish/Wish.jsx
  src/components/organisms/DetailReviewList/ReviewList.jsx
  src/components/organisms/JoinInput/JoinInput.jsx
  src/components/organisms/ReviewWrite/ReviewWrite.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyReviewPage/MyReviewPage.jsx
  src/pages/MyWishPage/MyWishPage.jsx
  src/store/useWishStore.js
Labels: 📮 API, 🎨 HTML & CSS, ✨ Feature, 📝 Docs, ✂️ Modify

#85 리뷰 컴포넌트 분리
  src/App.jsx
  src/components/atoms/ReviewButton/ReviewButton.jsx
  src/components/organisms/DetailReviewList/NoReview.jsx
  src/components/organisms/ReviewWrite/ReviewWrite.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyReviewPage/MyReviewPage.jsx
  src/pages/MyWishPage/MyWishPage.jsx
  src/pages/ReviewHashTagPage/ReviewHashTagPage.jsx
  src/routes/navigation.jsx
  src/store/useHashtagStore.js
  src/store/useLoginStore.js
Labels: 📮 API, 🎨 HTML & CSS, ✨ Feature
